format_version: 10
pipelines:
  test-hello-world-000:
    group: sample
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      git-1:
        git: https://github.com/harper182/my-app.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
      - Build-And-Test:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            Clean-Build:
              resources:
                - dev
              timeout: 0
              artifacts:
                - build:
                    source: base/terraform.tfplan
                    destination: tfplan
              tasks:
                - exec:
                    arguments:
                      - "hello"
                    command: echo 
                    run_if: passed
      
      - Serve-and-test: 
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          # approval:
          #   type: manual 
          #   allow_only_on_success: true
          jobs:    
            serve:
              resources:
                - dev
              timeout: 0
              tasks:
                - fetch:
                    stage: Build-And-Test
                    job: Clean-Build
                    source: tfplan
                    destination: base2/terraform.tfplan
                    is_file: yes
                - exec:
                    command: ls 
                    arguments:
                      - -al 
                    run_if: passed
                - exec:
                    command: tree 
                    arguments:
                      - base2
                    run_if: passed                
